services:
  tests:
    build:
      context: .
      args:
        - PHP_VERSION=8.3
    command: tail -f /dev/null
    environment:
      - PHPAR_PGSQL=pgsql://phpar:secret@postgres/phpar_test
      - PHPAR_MYSQL=mysql://phpar:secret@mysql/phpar_test
      - PHPAR_MARIADB=mysql://phpar:secret@mariadb/phpar_test
      - PHPAR_MEMCACHED=memcached
      - PHPAR_REDIS=redis://redis:6379
    depends_on:
      mysql:
        condition: service_healthy
      mariadb:
        condition: service_healthy
      postgres:
        condition: service_healthy
      memcached:
        condition: service_healthy
      redis:
        condition: service_healthy
  mysql:
    image: mysql:9.7
    environment:
      - MYSQL_USER=phpar
      - MYSQL_PASSWORD=secret
      - MYSQL_DATABASE=phpar_test
      - MYSQL_ROOT_PASSWORD=secret
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-psecret"]
      interval: 5s
      retries: 10
      timeout: 5s
  mariadb:
    image: mariadb:11.4
    environment:
      - MARIADB_USER=phpar
      - MARIADB_PASSWORD=secret
      - MARIADB_DATABASE=phpar_test
      - MARIADB_ROOT_PASSWORD=secret
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 5s
      retries: 10
      timeout: 5s
  postgres:
    image: postgres:18
    environment:
      - POSTGRES_DB=phpar_test
      - POSTGRES_USER=phpar
      - POSTGRES_PASSWORD=secret
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "phpar"]
      interval: 5s
      retries: 10
      timeout: 5s
  memcached:
    image: memcached:1.6
    healthcheck:
      test: ["CMD", "timeout", "5", "bash", "-c", "</dev/tcp/127.0.0.1/11211"]
      interval: 5s
      retries: 10
      timeout: 5s
  redis:
    image: redis:8
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      retries: 10
      timeout: 5s
