CREATE TABLE authors  (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT);
CREATE TABLE profiles (id INTEGER PRIMARY KEY AUTOINCREMENT, author_id INTEGER, bio TEXT);
CREATE TABLE posts    (id INTEGER PRIMARY KEY AUTOINCREMENT, author_id INTEGER, title TEXT);
CREATE TABLE comments (id INTEGER PRIMARY KEY AUTOINCREMENT, post_id INTEGER, body TEXT);
CREATE TABLE tags     (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT);
CREATE TABLE taggings (id INTEGER PRIMARY KEY AUTOINCREMENT, post_id INTEGER, tag_id INTEGER);
